version: "3.9"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
    # networks:
    #   - app_network
    ports:
      - "5434:5432"
    container_name: postgresdb

  # api:
  #   env_file:
  #     - .env
  #   networks:
  #     - app_network
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - db

networks:
  app_network:
volumes:
  db:
