name: Staging Deployment

on:
  push:
    branches:
    - 'release/**'

env:
  REGISTRY_HOST: 'registry.digitalocean.com/banach'
  IMAGE_NAME: 'pills-of-cs'
  TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
  NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkouts files
        uses: actions/checkout@v2.5.0
        with:
          token: ${{ secrets.PAT }}

      - name: Build image
        run: docker build -t $(echo $REGISTRY_HOST)/$(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7) -f Dockerfile .

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600

      - name: Push image to DigitalOcean Container Registry
        run: docker push $(echo $REGISTRY_HOST)/$(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7)

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to DO droplet via SSH action
        uses: appleboy/ssh-action@v0.1.3        
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          envs: REGISTRY_HOST,{{ secrets.DIGITALOCEAN_ACCESS_TOKEN }},TELEGRAM_TOKEN,NOTION_TOKEN,GITHUB_SHA,IMAGE_NAME
          script: |
          
            sudo DEBIAN_FRONTEND=noninteractive apt-get -yq upgrade
            sudo apt -y update && sudo apt upgrade
            sudo apt -y install docker-compose
            
            # Stop running container
            docker stop $(echo $IMAGE_NAME)

            # Remove old container
            docker rm $(echo $IMAGE_NAME)

            # Run a new container from a new image
            docker run -d \
            --restart always \
            --env TELEGRAM_TOKEN=$TELEGRAM_TOKEN \
            --env NOTION_TOKEN=$NOTION_TOKEN \
            --name $(echo $IMAGE_NAME) \
            $(echo $REGISTRY_HOST)/$(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7) make start
            
